version: '3.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /data/db
      #- mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo

#volumes:
  #mongo-data:
    #driver: local

  java-app:
    build: .
    ports:
      - 8085:8080
    environment:
      MONGO_DB: mongo
    depends_on:
      - mongo
