
name: Greeter

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: step 1, Greet
        run: echo ${{ secrets.KEY }}

      - name: step 2
        run: echo bye bye